--
-- Файл сгенерирован с помощью SQLiteStudio
--
-- Использованная кодировка текста: windows-1251
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: composition
CREATE TABLE composition (
    id        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    id_flavor INTEGER REFERENCES flavors (id_flavor) ON DELETE CASCADE ON UPDATE CASCADE,
    id_flower INTEGER REFERENCES flowers (id_flower) ON DELETE CASCADE ON UPDATE CASCADE,
    count     INTEGER
);

INSERT INTO composition (
                        id,
                        id_flavor,
                        id_flower,
                        count
                    )
                    VALUES (
                        1,
                        1,
                        1,
                        10
                    ),
                    (
                        2,
                        1,
                        2,
                        12
                    ),
                    (
                        3,
                        1,
                        3,
                        2
                    ),
                    (
                        4,
                        1,
                        4,
                        3
                    ),
                    (
                        5,
                        1,
                        5,
                        7
                    ),
                    (
                        6,
                        1,
                        6,
                        11
                    ),
                    (
                        7,
                        1,
                        7,
                        20
                    ),
                    (
                        8,
                        2,
                        5,
                        7
                    ),
                    (
                        9,
                        2,
                        1,
                        3
                    ),
                    (
                        10,
                        2,
                        6,
                        4
                    ),
                    (
                        11,
                        2,
                        2,
                        8
                    ),
                    (
                        12,
                        2,
                        16,
                        10
                    ),
                    (
                        13,
                        2,
                        8,
                        2
                    ),
                    (
                        14,
                        2,
                        18,
                        4
                    ),
                    (
                        15,
                        2,
                        17,
                        3
                    ),
                    (
                        16,
                        3,
                        6,
                        9
                    ),
                    (
                        17,
                        3,
                        1,
                        6
                    ),
                    (
                        18,
                        3,
                        5,
                        4
                    ),
                    (
                        19,
                        3,
                        8,
                        9
                    ),
                    (
                        20,
                        3,
                        9,
                        3
                    ),
                    (
                        21,
                        3,
                        10,
                        10
                    ),
                    (
                        22,
                        3,
                        11,
                        12
                    ),
                    (
                        23,
                        3,
                        12,
                        7
                    ),
                    (
                        24,
                        3,
                        2,
                        2
                    ),
                    (
                        25,
                        3,
                        13,
                        12
                    ),
                    (
                        26,
                        4,
                        5,
                        8
                    ),
                    (
                        27,
                        4,
                        14,
                        2
                    ),
                    (
                        28,
                        4,
                        6,
                        1
                    ),
                    (
                        29,
                        4,
                        4,
                        2
                    ),
                    (
                        30,
                        4,
                        15,
                        5
                    ),
                    (
                        31,
                        4,
                        11,
                        7
                    );

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
